namespace: terraform
repository: https://github.com/your-org/terraform-go
name: go
version: 1.0.0
readme: README.md
authors:
  - you@example.com
description: Terraform Go module via so file
license:
  - MIT
dependencies: {}